version: "3.8"

services:
  minecraft-server:
    image: sadpeppino/papermc
    build: .
    environment:
      MEMORY_ALLOC: "1G"
    tty: true
    ports:
      - 25565:25565
    volumes:
      - minecraft_server_data:/home/minecraft

volumes:
  minecraft_server_data:
